-- Gerando a tabela CLIENTE
CREATE TABLE Cliente
(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(25) NOT NULL,
	TELEFONE VARCHAR(12) NOT NULL,
	LOGRADOURO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(25) NOT NULL,
	CIDADE VARCHAR(25) NOT NULL,
	ESTADO VARCHAR(25) NOT NULL,
);